### PR TITLE
Added support for PHL08DC (Philips 221P6QPYES/00)

### PR DESCRIPTION
**Pull request by kravemir**
Added monitor profile and tested base vcp. File `doc/monitors/PHL08DC.md` contains testing documentation and checklist. I did squash small incremental commits created during testing.

### CODE REVIEW

**Comment by kravemir** [comment]
Issue: #20

**Comment by kravemir** [comment]
Don't merge it yet. I'll finish the monitor profile once I will have finished other duties/responsibilities.

**Comment by larstobi** [comment]
Great! Thanks @kravemir !

**Comment by kravemir** [comment]
I'm glad, that the model descriptor for my monitor is in the repository!

**Pull request merged**
